trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  artifactName: 'my-app'
  artifactPath: '$(Build.ArtifactStagingDirectory)/$(artifactName).zip'
  vmUserName: 'azureuser'
  vmPassword: 'Abkbaas@3668554'
  vmIpAddress: '10.0.0.4'
  sshPublicKey: 'azurekey.pub'
  sshPrivateKey: 'azurekey'

steps:
- task: ArchiveFiles@2
  displayName: 'Archive Files'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: true
    archiveFile: '$(artifactPath)'
    replaceExistingArchive: true

- task: SCPUpload@1
  displayName: 'Upload Artifacts to VM'
  inputs:
    serverEndpoint: '<your-vm-name>'
    source: '$(artifactPath)'
    destination: '/tmp/$(artifactName).zip'
    cleanDestinationFolder: true
    sshPrivateKey: '$(sshPrivateKey)'

- task: SSH@0
  displayName: 'Extract Artifacts on VM'
  inputs:
    sshEndpoint: '$(vmIpAddress):22'
    username: '$(vmUserName)'
    password: '$(vmPassword)'
    privateKey: '$(sshPrivateKey)'
    scriptType: 'inline'
    inline: |
      cd /var/www/myapp
      sudo unzip -o /tmp/$(artifactName).zip -d .
      sudo chown -R www-data:www-data .

- task: SSH@0
  displayName: 'Restart Apache on VM'
  inputs:
    sshEndpoint: '$(vmIpAddress):22'
    username: '$(vmUserName)'
    password: '$(vmPassword)'
    privateKey: '$(sshPrivateKey)'
    scriptType: 'inline'
    inline: |
      sudo systemctl restart apache2
